name: Unit Tests
# This determines what event triggers the tests  
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 
# This determines what OS runs the tests  
jobs:
  test:
    runs-on: ubuntu-latest
    # This determines what steps are taken before the tests  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install  
      # This runs the tests  
      - name: Unit tests
        run: npm Unit tests
